/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import javax.swing.ImageIcon;
import javax.swing.ScrollPaneConstants;
import controlador.*;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import vistas_paneles.*;
import tabla.EstiloTablaHeader;
import tabla.EstiloTablaRenderer;
import tabla.MyScrollbarUI;
import vistas_paneles.*;

/**
 *
 * @author Danilo
 */
public class Principal extends javax.swing.JFrame {

    public Matriculas mat = new Matriculas();
    int pos = 0;
    public int menu_calificaciones=0;
    public int sub_menu_calificaciones=0;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(this);
        setIconImage(new ImageIcon(getClass().getResource("../Img_menu/SEPRYTSAV_45x45PX.png")).getImage());

// aqui cambiamos colores del scroll bar
        sc_menu.getVerticalScrollBar().setUI(new MyScrollbarUI());
        sc_menu.getHorizontalScrollBar().setUI(new MyScrollbarUI());

        sc_ventanas.getVerticalScrollBar().setUI(new MyScrollbarUI());
        sc_ventanas.getHorizontalScrollBar().setUI(new MyScrollbarUI());
        //quitamos la seleccion del boton
        nofocus();

        // CambiaPanel p=new CambiaPanel(panel_master, new vistas_paneles.Panel_Home());
        // new CambiaPanel(panel_master, new vistas_paneles.pnlHome());
        Panel_Home p_home = new Panel_Home();
        new cambia_panel(panel_master, p_home);

//     panel_master.setLayout(new java.awt.BorderLayout());
//            panel_master.add(p_home);
//
//            panel_master.validate();
        cerrar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_menu_calificaciones = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_menu = new javax.swing.JButton();
        panel_menu = new javax.swing.JPanel();
        sc_menu = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_cursos = new rojerusan.RSButtonMetro();
        jLabel3 = new javax.swing.JLabel();
        btn_home = new rojerusan.RSButtonMetro();
        btn_diplomados = new rojerusan.RSButtonMetro();
        btn_congresos = new rojerusan.RSButtonMetro();
        btn_oec = new rojerusan.RSButtonMetro();
        btn_licencias = new rojerusan.RSButtonMetro();
        btn_seminarios = new rojerusan.RSButtonMetro();
        btn_matriculas = new rojerusan.RSButtonMetro();
        btn_inscriptions = new rojerusan.RSButtonMetro();
        btn_estudents = new rojerusan.RSButtonMetro();
        btn_peri_aca = new rojerusan.RSButtonMetro();
        btn_crono_cali = new rojerusan.RSButtonMetro();
        btn_crono_act = new rojerusan.RSButtonMetro();
        btn_horarios = new rojerusan.RSButtonMetro();
        jLabel4 = new javax.swing.JLabel();
        btn_califications = new rojerusan.RSButtonMetro();
        jLabel5 = new javax.swing.JLabel();
        btn_docente = new rojerusan.RSButtonMetro();
        sc_ventanas = new javax.swing.JScrollPane();
        panel_master = new javax.swing.JPanel();

        panel_menu_calificaciones.setBackground(new java.awt.Color(255, 0, 51));
        panel_menu_calificaciones.setAlignmentX(4.0F);
        panel_menu_calificaciones.setAlignmentY(4.0F);

        javax.swing.GroupLayout panel_menu_calificacionesLayout = new javax.swing.GroupLayout(panel_menu_calificaciones);
        panel_menu_calificaciones.setLayout(panel_menu_calificacionesLayout);
        panel_menu_calificacionesLayout.setHorizontalGroup(
            panel_menu_calificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );
        panel_menu_calificacionesLayout.setVerticalGroup(
            panel_menu_calificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(21, 96, 136));
        jPanel2.setForeground(new java.awt.Color(21, 96, 136));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MENÚ");

        btn_menu.setBackground(new java.awt.Color(21, 96, 136));
        btn_menu.setForeground(new java.awt.Color(21, 96, 136));
        btn_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_menu/icons8_Menu_52px_1.png"))); // NOI18N
        btn_menu.setBorder(null);
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        panel_menu.setBackground(new java.awt.Color(38, 166, 154));

        sc_menu.setBackground(new java.awt.Color(27, 108, 155));
        sc_menu.setBorder(null);
        sc_menu.setForeground(new java.awt.Color(27, 108, 155));
        sc_menu.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        sc_menu.setToolTipText("");
        sc_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel3.setBackground(new java.awt.Color(27, 108, 155));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Académia");

        btn_cursos.setBackground(new java.awt.Color(27, 108, 155));
        btn_cursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_menu/cursos_52px.png"))); // NOI18N
        btn_cursos.setText("         CURSOS           ");
        btn_cursos.setActionCommand("          ");
        btn_cursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cursosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Educación Continua");

        btn_home.setBackground(new java.awt.Color(21, 96, 136));
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_menu/home_52px.png"))); // NOI18N
        btn_home.setText("         HOME                   ");
        btn_home.setActionCommand("          ");
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        btn_diplomados.setBackground(new java.awt.Color(27, 108, 155));
        btn_diplomados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_menu/diplomados_52px.png"))); // NOI18N
        btn_diplomados.setText("          DIPLOMADOS   ");
        btn_diplomados.setActionCommand("          ");
        btn_diplomados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_diplomadosActionPerformed(evt);
            }
        });

        btn_congresos.setBackground(new java.awt.Color(27, 108, 155));
        btn_congresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_menu/congresos_52px.png"))); // NOI18N
        btn_congresos.setText("         CONGRESOS      ");
        btn_congresos.setActionCommand("          ");
        btn_congresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_congresosActionPerformed(evt);
            }
        });

        btn_oec.setBackground(new java.awt.Color(27, 108, 155));
        btn_oec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_menu/oec_52px.png"))); // NOI18N
        btn_oec.setText("         OEC                      ");
        btn_oec.setActionCommand("          ");
        btn_oec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_oecActionPerformed(evt);
            }
        });

        btn_licencias.setBackground(new java.awt.Color(27, 108, 155));
        btn_licencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_menu/licencias_52px.png"))); // NOI18N
        btn_licencias.setText("          LICENCIAS         ");
        btn_licencias.setActionCommand("          ");
        btn_licencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_licenciasActionPerformed(evt);
            }
        });

        btn_seminarios.setBackground(new java.awt.Color(27, 108, 155));
        btn_seminarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_menu/Seminarios.png"))); // NOI18N
        btn_seminarios.setText("         SEMINARIOS        ");
        btn_seminarios.setActionCommand("          ");
        btn_seminarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seminariosActionPerformed(evt);
            }
        });

        btn_matriculas.setBackground(new java.awt.Color(27, 108, 155));
        btn_matriculas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_menu/matriculas_52px.png"))); // NOI18N
        btn_matriculas.setText("         MATRÍCULAS         ");
        btn_matriculas.setActionCommand("          ");
        btn_matriculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_matriculasActionPerformed(evt);
            }
        });

        btn_inscriptions.setBackground(new java.awt.Color(27, 108, 155));
        btn_inscriptions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_menu/Inscription_52px.png"))); // NOI18N
        btn_inscriptions.setText("         INSCRIPCIONES");
        btn_inscriptions.setActionCommand("          ");
        btn_inscriptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inscriptionsActionPerformed(evt);
            }
        });

        btn_estudents.setBackground(new java.awt.Color(27, 108, 155));
        btn_estudents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_menu/Estudiantes__52px.png"))); // NOI18N
        btn_estudents.setText("         ESTUDIANTES      ");
        btn_estudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_estudentsActionPerformed(evt);
            }
        });

        btn_peri_aca.setBackground(new java.awt.Color(27, 108, 155));
        btn_peri_aca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_menu/periodo_acade_52px.png"))); // NOI18N
        btn_peri_aca.setText("       PERIODO ACADEMICO                         ");
        btn_peri_aca.setActionCommand("         PERIODO ACA");
        btn_peri_aca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_peri_acaActionPerformed(evt);
            }
        });

        btn_crono_cali.setBackground(new java.awt.Color(27, 108, 155));
        btn_crono_cali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_menu/crono_cali_52px.png"))); // NOI18N
        btn_crono_cali.setText("      CRONOGRAMA DE CALIFICACIONES");
        btn_crono_cali.setActionCommand("         PERIODO ACA");
        btn_crono_cali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crono_caliActionPerformed(evt);
            }
        });

        btn_crono_act.setBackground(new java.awt.Color(27, 108, 155));
        btn_crono_act.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_menu/cron_activi_52px_1.png"))); // NOI18N
        btn_crono_act.setText("        CRONOGRAMA DE ACTIVIDADES      ");
        btn_crono_act.setActionCommand("");
        btn_crono_act.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crono_actActionPerformed(evt);
            }
        });

        btn_horarios.setBackground(new java.awt.Color(27, 108, 155));
        btn_horarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_menu/horarios_52px.png"))); // NOI18N
        btn_horarios.setText("         HORARIOS           ");
        btn_horarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_horariosActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MENÚ");

        btn_califications.setBackground(new java.awt.Color(27, 108, 155));
        btn_califications.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_menu/calificaciones_52px.png"))); // NOI18N
        btn_califications.setText("        CALIFICACIONES                                 ");
        btn_califications.setActionCommand("");
        btn_califications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calificationsActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" Home");

        btn_docente.setBackground(new java.awt.Color(27, 108, 155));
        btn_docente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_menu/Docentes_52px.png"))); // NOI18N
        btn_docente.setText("         DOCENTES         ");
        btn_docente.setActionCommand("          ");
        btn_docente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_docenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cursos, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_diplomados, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_congresos, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_oec, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_licencias, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_seminarios, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_matriculas, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_inscriptions, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_estudents, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_horarios, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(btn_peri_aca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_crono_cali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_crono_act, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_califications, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLabel4))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addComponent(btn_docente, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 125, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(36, 36, 36)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_califications, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btn_crono_cali, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_crono_act, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_docente, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_estudents, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_horarios, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_peri_aca, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_cursos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_congresos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_diplomados, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_licencias, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btn_seminarios, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_oec, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_inscriptions, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_matriculas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sc_menu.setViewportView(jPanel3);

        javax.swing.GroupLayout panel_menuLayout = new javax.swing.GroupLayout(panel_menu);
        panel_menu.setLayout(panel_menuLayout);
        panel_menuLayout.setHorizontalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sc_menu, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
        );
        panel_menuLayout.setVerticalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sc_menu, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
        );

        panel_master.setBackground(new java.awt.Color(255, 255, 255));
        panel_master.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        javax.swing.GroupLayout panel_masterLayout = new javax.swing.GroupLayout(panel_master);
        panel_master.setLayout(panel_masterLayout);
        panel_masterLayout.setHorizontalGroup(
            panel_masterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 996, Short.MAX_VALUE)
        );
        panel_masterLayout.setVerticalGroup(
            panel_masterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );

        sc_ventanas.setViewportView(panel_master);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panel_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sc_ventanas, javax.swing.GroupLayout.PREFERRED_SIZE, 1126, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sc_ventanas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cursosActionPerformed
        // TODO add your handling code here:
        pintar(9);
        
        Cursos cur= new Cursos();
        new cambia_panel(panel_master, cur);
    }//GEN-LAST:event_btn_cursosActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
        pintar(1);

        Panel_Home p_home = new Panel_Home();
        new cambia_panel(panel_master, p_home);
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_diplomadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_diplomadosActionPerformed
        // TODO add your handling code here:
        pintar(11);
        Diplomados dip = new Diplomados();
        new cambia_panel(panel_master, dip);
    }//GEN-LAST:event_btn_diplomadosActionPerformed

    private void btn_congresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_congresosActionPerformed
        // TODO add your handling code here:
        pintar(10);
         Congresos con= new Congresos();
        new cambia_panel(panel_master, con);

    }//GEN-LAST:event_btn_congresosActionPerformed

    private void btn_oecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_oecActionPerformed
        // TODO add your handling code here:
        pintar(14);
    }//GEN-LAST:event_btn_oecActionPerformed

    private void btn_licenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_licenciasActionPerformed
        // TODO add your handling code here:
        pintar(12);
        Licencias lic= new  Licencias();
        new cambia_panel(panel_master, lic);
    }//GEN-LAST:event_btn_licenciasActionPerformed

    private void btn_seminariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seminariosActionPerformed
        // TODO add your handling code here:
        pintar(13);
         Seminarios sem= new Seminarios();
        new cambia_panel(panel_master, sem);
    }//GEN-LAST:event_btn_seminariosActionPerformed

    private void btn_matriculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_matriculasActionPerformed
        // TODO add your handling code here:
        pintar(16);

        new cambia_panel(panel_master, mat);
    }//GEN-LAST:event_btn_matriculasActionPerformed

    private void btn_inscriptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inscriptionsActionPerformed
        // TODO add your handling code here:
        pintar(15);
    }//GEN-LAST:event_btn_inscriptionsActionPerformed

    private void btn_estudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_estudentsActionPerformed
        // TODO add your handling code here:
        pintar(6);
        Estudiantes est = new Estudiantes();

        new cambia_panel(panel_master, est);
    }//GEN-LAST:event_btn_estudentsActionPerformed

    private void btn_peri_acaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_peri_acaActionPerformed
        // TODO add your handling code here:
        pintar(8);

        Periodo_Academico pe = new Periodo_Academico();
        new cambia_panel(panel_master, pe);
    }//GEN-LAST:event_btn_peri_acaActionPerformed

    private void btn_crono_caliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crono_caliActionPerformed
        // TODO add your handling code here:
        pintar(3);
    }//GEN-LAST:event_btn_crono_caliActionPerformed

    private void btn_crono_actActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crono_actActionPerformed
        // TODO add your handling code here:
        pintar(4);

    }//GEN-LAST:event_btn_crono_actActionPerformed

    private void btn_horariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_horariosActionPerformed
        // TODO add your handling code here:
        pintar(7);
        Horarios hor = new Horarios();
        new cambia_panel(panel_master, hor);
    }//GEN-LAST:event_btn_horariosActionPerformed

    private void btn_calificationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calificationsActionPerformed
        // TODO add your handling code here:
        pintar(2);
        // capturamos la pos del mause
        Point punto = MouseInfo.getPointerInfo().getLocation();
        int x1 = punto.x;
        int y1 = punto.y;

        
      

        Menu_calificaciones m = new Menu_calificaciones(this, true);
        m.setLocation(x1, y1);
        m.setVisible(true);


    }//GEN-LAST:event_btn_calificationsActionPerformed

    private void btn_docenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_docenteActionPerformed
        // TODO add your handling code here:
        pintar(5);

        Docentes docente = new Docentes();

        new cambia_panel(panel_master, docente);


    }//GEN-LAST:event_btn_docenteActionPerformed

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed

        int posicion = panel_menu.getX();
        if (posicion > -1) {
            Animacion.Animacion.mover_izquierda(0, -264, 2, 2, panel_menu);
        } else {
            Animacion.Animacion.mover_derecha(-264, 0, 2, 2, panel_menu);

            //           x,x,velocidad entre mas es menos
        }
        int pos = panel_menu_calificaciones.getX();
        if (pos > -1) {
            Animacion.Animacion.mover_derecha(-264, 0, 2, 2, panel_menu_calificaciones);
        } else {

            Animacion.Animacion.mover_izquierda(0, -264, 2, 2, panel_menu_calificaciones);

            //           x,x,velocidad entre mas es menos
        }

    }//GEN-LAST:event_btn_menuActionPerformed

    public void pintar(int pos_mouse) {
        int pos = pos_mouse;
        Color c_precionado = new java.awt.Color(21, 96, 136);
        Color c_sinprecionar = new java.awt.Color(27, 108, 155);

        if (pos == 1) {
            btn_home.setBackground(c_precionado);              //1
            btn_califications.setBackground(c_sinprecionar);   //2
            btn_crono_cali.setBackground(c_sinprecionar);      //3
            btn_crono_act.setBackground(c_sinprecionar);       //4
            btn_docente.setBackground(c_sinprecionar);         //5

            btn_estudents.setBackground(c_sinprecionar);       //6
            btn_horarios.setBackground(c_sinprecionar);        //7
            btn_peri_aca.setBackground(c_sinprecionar);        //8
            btn_cursos.setBackground(c_sinprecionar);         //9

            btn_congresos.setBackground(c_sinprecionar);      //10
            btn_diplomados.setBackground(c_sinprecionar);     //11
            btn_licencias.setBackground(c_sinprecionar);     //12
            btn_seminarios.setBackground(c_sinprecionar);    //13

            btn_oec.setBackground(c_sinprecionar);          //14
            btn_inscriptions.setBackground(c_sinprecionar);  //15
            btn_matriculas.setBackground(c_sinprecionar);    //16

        }
        if (pos == 2) {
            btn_home.setBackground(c_sinprecionar);              //1
            btn_califications.setBackground(c_precionado);   //2
            btn_crono_cali.setBackground(c_sinprecionar);      //3
            btn_crono_act.setBackground(c_sinprecionar);       //4
            btn_docente.setBackground(c_sinprecionar);         //5

            btn_estudents.setBackground(c_sinprecionar);       //6
            btn_horarios.setBackground(c_sinprecionar);        //7
            btn_peri_aca.setBackground(c_sinprecionar);        //8
            btn_cursos.setBackground(c_sinprecionar);         //9

            btn_congresos.setBackground(c_sinprecionar);      //10
            btn_diplomados.setBackground(c_sinprecionar);     //11
            btn_licencias.setBackground(c_sinprecionar);     //12
            btn_seminarios.setBackground(c_sinprecionar);    //13

            btn_oec.setBackground(c_sinprecionar);          //14
            btn_inscriptions.setBackground(c_sinprecionar);  //15
            btn_matriculas.setBackground(c_sinprecionar);    //16

        }
        if (pos == 3) {
            btn_home.setBackground(c_sinprecionar);              //1
            btn_califications.setBackground(c_sinprecionar);   //2
            btn_crono_cali.setBackground(c_precionado);      //3
            btn_crono_act.setBackground(c_sinprecionar);       //4
            btn_docente.setBackground(c_sinprecionar);         //5

            btn_estudents.setBackground(c_sinprecionar);       //6
            btn_horarios.setBackground(c_sinprecionar);        //7
            btn_peri_aca.setBackground(c_sinprecionar);        //8
            btn_cursos.setBackground(c_sinprecionar);         //9

            btn_congresos.setBackground(c_sinprecionar);      //10
            btn_diplomados.setBackground(c_sinprecionar);     //11
            btn_licencias.setBackground(c_sinprecionar);     //12
            btn_seminarios.setBackground(c_sinprecionar);    //13

            btn_oec.setBackground(c_sinprecionar);          //14
            btn_inscriptions.setBackground(c_sinprecionar);  //15
            btn_matriculas.setBackground(c_sinprecionar);    //16

        }
        if (pos == 4) {
            btn_home.setBackground(c_sinprecionar);              //1
            btn_califications.setBackground(c_sinprecionar);   //2
            btn_crono_cali.setBackground(c_sinprecionar);      //3
            btn_crono_act.setBackground(c_precionado);       //4
            btn_docente.setBackground(c_sinprecionar);         //5

            btn_estudents.setBackground(c_sinprecionar);       //6
            btn_horarios.setBackground(c_sinprecionar);        //7
            btn_peri_aca.setBackground(c_sinprecionar);        //8
            btn_cursos.setBackground(c_sinprecionar);         //9

            btn_congresos.setBackground(c_sinprecionar);      //10
            btn_diplomados.setBackground(c_sinprecionar);     //11
            btn_licencias.setBackground(c_sinprecionar);     //12
            btn_seminarios.setBackground(c_sinprecionar);    //13

            btn_oec.setBackground(c_sinprecionar);          //14
            btn_inscriptions.setBackground(c_sinprecionar);  //15
            btn_matriculas.setBackground(c_sinprecionar);    //16

        }
        if (pos == 5) {
            btn_home.setBackground(c_sinprecionar);              //1
            btn_califications.setBackground(c_sinprecionar);   //2
            btn_crono_cali.setBackground(c_sinprecionar);      //3
            btn_crono_act.setBackground(c_sinprecionar);       //4
            btn_docente.setBackground(c_precionado);         //5

            btn_estudents.setBackground(c_sinprecionar);       //6
            btn_horarios.setBackground(c_sinprecionar);        //7
            btn_peri_aca.setBackground(c_sinprecionar);        //8
            btn_cursos.setBackground(c_sinprecionar);         //9

            btn_congresos.setBackground(c_sinprecionar);      //10
            btn_diplomados.setBackground(c_sinprecionar);     //11
            btn_licencias.setBackground(c_sinprecionar);     //12
            btn_seminarios.setBackground(c_sinprecionar);    //13

            btn_oec.setBackground(c_sinprecionar);          //14
            btn_inscriptions.setBackground(c_sinprecionar);  //15
            btn_matriculas.setBackground(c_sinprecionar);    //16

        }
        if (pos == 6) {
            btn_home.setBackground(c_sinprecionar);              //1
            btn_califications.setBackground(c_sinprecionar);   //2
            btn_crono_cali.setBackground(c_sinprecionar);      //3
            btn_crono_act.setBackground(c_sinprecionar);       //4
            btn_docente.setBackground(c_sinprecionar);         //5

            btn_estudents.setBackground(c_precionado);       //6
            btn_horarios.setBackground(c_sinprecionar);        //7
            btn_peri_aca.setBackground(c_sinprecionar);        //8
            btn_cursos.setBackground(c_sinprecionar);         //9

            btn_congresos.setBackground(c_sinprecionar);      //10
            btn_diplomados.setBackground(c_sinprecionar);     //11
            btn_licencias.setBackground(c_sinprecionar);     //12
            btn_seminarios.setBackground(c_sinprecionar);    //13

            btn_oec.setBackground(c_sinprecionar);          //14
            btn_inscriptions.setBackground(c_sinprecionar);  //15
            btn_matriculas.setBackground(c_sinprecionar);    //16

        }
        if (pos == 7) {
            btn_home.setBackground(c_sinprecionar);              //1
            btn_califications.setBackground(c_sinprecionar);   //2
            btn_crono_cali.setBackground(c_sinprecionar);      //3
            btn_crono_act.setBackground(c_sinprecionar);       //4
            btn_docente.setBackground(c_sinprecionar);         //5

            btn_estudents.setBackground(c_sinprecionar);       //6
            btn_horarios.setBackground(c_precionado);        //7
            btn_peri_aca.setBackground(c_sinprecionar);        //8
            btn_cursos.setBackground(c_sinprecionar);         //9

            btn_congresos.setBackground(c_sinprecionar);      //10
            btn_diplomados.setBackground(c_sinprecionar);     //11
            btn_licencias.setBackground(c_sinprecionar);     //12
            btn_seminarios.setBackground(c_sinprecionar);    //13

            btn_oec.setBackground(c_sinprecionar);          //14
            btn_inscriptions.setBackground(c_sinprecionar);  //15
            btn_matriculas.setBackground(c_sinprecionar);    //16

        }
        if (pos == 8) {
            btn_home.setBackground(c_sinprecionar);              //1
            btn_califications.setBackground(c_sinprecionar);   //2
            btn_crono_cali.setBackground(c_sinprecionar);      //3
            btn_crono_act.setBackground(c_sinprecionar);       //4
            btn_docente.setBackground(c_sinprecionar);         //5

            btn_estudents.setBackground(c_sinprecionar);       //6
            btn_horarios.setBackground(c_sinprecionar);        //7
            btn_peri_aca.setBackground(c_precionado);        //8
            btn_cursos.setBackground(c_sinprecionar);         //9

            btn_congresos.setBackground(c_sinprecionar);      //10
            btn_diplomados.setBackground(c_sinprecionar);     //11
            btn_licencias.setBackground(c_sinprecionar);     //12
            btn_seminarios.setBackground(c_sinprecionar);    //13

            btn_oec.setBackground(c_sinprecionar);          //14
            btn_inscriptions.setBackground(c_sinprecionar);  //15
            btn_matriculas.setBackground(c_sinprecionar);    //16

        }
        if (pos == 9) {
            btn_home.setBackground(c_sinprecionar);              //1
            btn_califications.setBackground(c_sinprecionar);   //2
            btn_crono_cali.setBackground(c_sinprecionar);      //3
            btn_crono_act.setBackground(c_sinprecionar);       //4
            btn_docente.setBackground(c_sinprecionar);         //5

            btn_estudents.setBackground(c_sinprecionar);       //6
            btn_horarios.setBackground(c_sinprecionar);        //7
            btn_peri_aca.setBackground(c_sinprecionar);        //8
            btn_cursos.setBackground(c_precionado);         //9

            btn_congresos.setBackground(c_sinprecionar);      //10
            btn_diplomados.setBackground(c_sinprecionar);     //11
            btn_licencias.setBackground(c_sinprecionar);     //12
            btn_seminarios.setBackground(c_sinprecionar);    //13

            btn_oec.setBackground(c_sinprecionar);          //14
            btn_inscriptions.setBackground(c_sinprecionar);  //15
            btn_matriculas.setBackground(c_sinprecionar);    //16

        }
        if (pos == 10) {
            btn_home.setBackground(c_sinprecionar);              //1
            btn_califications.setBackground(c_sinprecionar);   //2
            btn_crono_cali.setBackground(c_sinprecionar);      //3
            btn_crono_act.setBackground(c_sinprecionar);       //4
            btn_docente.setBackground(c_sinprecionar);         //5

            btn_estudents.setBackground(c_sinprecionar);       //6
            btn_horarios.setBackground(c_sinprecionar);        //7
            btn_peri_aca.setBackground(c_sinprecionar);        //8
            btn_cursos.setBackground(c_sinprecionar);         //9

            btn_congresos.setBackground(c_precionado);      //10
            btn_diplomados.setBackground(c_sinprecionar);     //11
            btn_licencias.setBackground(c_sinprecionar);     //12
            btn_seminarios.setBackground(c_sinprecionar);    //13

            btn_oec.setBackground(c_sinprecionar);          //14
            btn_inscriptions.setBackground(c_sinprecionar);  //15
            btn_matriculas.setBackground(c_sinprecionar);    //16

        }
        if (pos == 11) {
            btn_home.setBackground(c_sinprecionar);              //1
            btn_califications.setBackground(c_sinprecionar);   //2
            btn_crono_cali.setBackground(c_sinprecionar);      //3
            btn_crono_act.setBackground(c_sinprecionar);       //4
            btn_docente.setBackground(c_sinprecionar);         //5

            btn_estudents.setBackground(c_sinprecionar);       //6
            btn_horarios.setBackground(c_sinprecionar);        //7
            btn_peri_aca.setBackground(c_sinprecionar);        //8
            btn_cursos.setBackground(c_sinprecionar);         //9

            btn_congresos.setBackground(c_sinprecionar);      //10
            btn_diplomados.setBackground(c_precionado);     //11
            btn_licencias.setBackground(c_sinprecionar);     //12
            btn_seminarios.setBackground(c_sinprecionar);    //13

            btn_oec.setBackground(c_sinprecionar);          //14
            btn_inscriptions.setBackground(c_sinprecionar);  //15
            btn_matriculas.setBackground(c_sinprecionar);    //16

        }

        if (pos == 12) {
            btn_home.setBackground(c_sinprecionar);              //1
            btn_califications.setBackground(c_sinprecionar);   //2
            btn_crono_cali.setBackground(c_sinprecionar);      //3
            btn_crono_act.setBackground(c_sinprecionar);       //4
            btn_docente.setBackground(c_sinprecionar);         //5

            btn_estudents.setBackground(c_sinprecionar);       //6
            btn_horarios.setBackground(c_sinprecionar);        //7
            btn_peri_aca.setBackground(c_sinprecionar);        //8
            btn_cursos.setBackground(c_sinprecionar);         //9

            btn_congresos.setBackground(c_sinprecionar);      //10
            btn_diplomados.setBackground(c_sinprecionar);     //11
            btn_licencias.setBackground(c_precionado);     //12
            btn_seminarios.setBackground(c_sinprecionar);    //13

            btn_oec.setBackground(c_sinprecionar);          //14
            btn_inscriptions.setBackground(c_sinprecionar);  //15
            btn_matriculas.setBackground(c_sinprecionar);    //16

        }
        if (pos == 13) {
            btn_home.setBackground(c_sinprecionar);              //1
            btn_califications.setBackground(c_sinprecionar);   //2
            btn_crono_cali.setBackground(c_sinprecionar);      //3
            btn_crono_act.setBackground(c_sinprecionar);       //4
            btn_docente.setBackground(c_sinprecionar);         //5

            btn_estudents.setBackground(c_sinprecionar);       //6
            btn_horarios.setBackground(c_sinprecionar);        //7
            btn_peri_aca.setBackground(c_sinprecionar);        //8
            btn_cursos.setBackground(c_sinprecionar);         //9

            btn_congresos.setBackground(c_sinprecionar);      //10
            btn_diplomados.setBackground(c_sinprecionar);     //11
            btn_licencias.setBackground(c_sinprecionar);     //12
            btn_seminarios.setBackground(c_precionado);    //13

            btn_oec.setBackground(c_sinprecionar);          //14
            btn_inscriptions.setBackground(c_sinprecionar);  //15
            btn_matriculas.setBackground(c_sinprecionar);    //16

        }
        if (pos == 14) {
            btn_home.setBackground(c_sinprecionar);              //1
            btn_califications.setBackground(c_sinprecionar);   //2
            btn_crono_cali.setBackground(c_sinprecionar);      //3
            btn_crono_act.setBackground(c_sinprecionar);       //4
            btn_docente.setBackground(c_sinprecionar);         //5

            btn_estudents.setBackground(c_sinprecionar);       //6
            btn_horarios.setBackground(c_sinprecionar);        //7
            btn_peri_aca.setBackground(c_sinprecionar);        //8
            btn_cursos.setBackground(c_sinprecionar);         //9

            btn_congresos.setBackground(c_sinprecionar);      //10
            btn_diplomados.setBackground(c_sinprecionar);     //11
            btn_licencias.setBackground(c_sinprecionar);     //12
            btn_seminarios.setBackground(c_sinprecionar);    //13

            btn_oec.setBackground(c_precionado);          //14
            btn_inscriptions.setBackground(c_sinprecionar);  //15
            btn_matriculas.setBackground(c_sinprecionar);    //16

        }
        if (pos == 15) {
            btn_home.setBackground(c_sinprecionar);              //1
            btn_califications.setBackground(c_sinprecionar);   //2
            btn_crono_cali.setBackground(c_sinprecionar);      //3
            btn_crono_act.setBackground(c_sinprecionar);       //4
            btn_docente.setBackground(c_sinprecionar);         //5

            btn_estudents.setBackground(c_sinprecionar);       //6
            btn_horarios.setBackground(c_sinprecionar);        //7
            btn_peri_aca.setBackground(c_sinprecionar);        //8
            btn_cursos.setBackground(c_sinprecionar);         //9

            btn_congresos.setBackground(c_sinprecionar);      //10
            btn_diplomados.setBackground(c_sinprecionar);     //11
            btn_licencias.setBackground(c_sinprecionar);     //12
            btn_seminarios.setBackground(c_sinprecionar);    //13

            btn_oec.setBackground(c_sinprecionar);          //14
            btn_inscriptions.setBackground(c_precionado);  //15
            btn_matriculas.setBackground(c_sinprecionar);    //16

        }
        if (pos == 16) {
            btn_home.setBackground(c_sinprecionar);              //1
            btn_califications.setBackground(c_sinprecionar);   //2
            btn_crono_cali.setBackground(c_sinprecionar);      //3
            btn_crono_act.setBackground(c_sinprecionar);       //4
            btn_docente.setBackground(c_sinprecionar);         //5

            btn_estudents.setBackground(c_sinprecionar);       //6
            btn_horarios.setBackground(c_sinprecionar);        //7
            btn_peri_aca.setBackground(c_sinprecionar);        //8
            btn_cursos.setBackground(c_sinprecionar);         //9

            btn_congresos.setBackground(c_sinprecionar);      //10
            btn_diplomados.setBackground(c_sinprecionar);     //11
            btn_licencias.setBackground(c_sinprecionar);     //12
            btn_seminarios.setBackground(c_sinprecionar);    //13

            btn_oec.setBackground(c_sinprecionar);          //14
            btn_inscriptions.setBackground(c_sinprecionar);  //15
            btn_matriculas.setBackground(c_precionado);    //16

        }

    }

    private void nofocus() {
        btn_menu.setFocusPainted(false);
        btn_home.setFocusPainted(false);;              //1
        btn_califications.setFocusPainted(false);   //2
        btn_crono_cali.setFocusPainted(false);      //3
        btn_crono_act.setFocusPainted(false);       //4
        btn_docente.setFocusPainted(false);      //5

        btn_estudents.setFocusPainted(false);       //6
        btn_horarios.setFocusPainted(false);       //7
        btn_peri_aca.setFocusPainted(false);        //8
        btn_cursos.setFocusPainted(false);       //9

        btn_congresos.setFocusPainted(false);      //10
        btn_diplomados.setFocusPainted(false);     //11
        btn_licencias.setFocusPainted(false);     //12
        btn_seminarios.setFocusPainted(false);    //13

        btn_oec.setFocusPainted(false);         //14
        btn_inscriptions.setFocusPainted(false);  //15
        btn_matriculas.setFocusPainted(false);   //16
    }

//////////// validar la salida
    public void cerrar() {
        try {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            //this.setResizable (false);
            addWindowListener(new WindowAdapter() {
                public void windowClosing(WindowEvent e) {
                    int res = confirmar("Alerta", "Esta Seguro que desea salir de la aplicación", "/Img_alertas/Error_100px.png");

                    if (res == 1) {
                        System.exit(0);

                    }

                }
            });
            this.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public int confirmar(String titulo, String texto, String dir_img) {

        int estatus = 9;
        Alertas wa = new Alertas(null, true);
        wa.txt_titu.setText(titulo);
        wa.txt_txt.setText(texto);

        wa.txt_img.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir_img)));

        wa.setVisible(true);

        estatus = wa.respuesta;

        return estatus;
    }
    public void openwindows_calificaciones(int valor){
     if(valor==1){
         
     }   
    }
    
    
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonMetro btn_califications;
    private rojerusan.RSButtonMetro btn_congresos;
    private rojerusan.RSButtonMetro btn_crono_act;
    private rojerusan.RSButtonMetro btn_crono_cali;
    private rojerusan.RSButtonMetro btn_cursos;
    private rojerusan.RSButtonMetro btn_diplomados;
    private rojerusan.RSButtonMetro btn_docente;
    private rojerusan.RSButtonMetro btn_estudents;
    private rojerusan.RSButtonMetro btn_home;
    private rojerusan.RSButtonMetro btn_horarios;
    private rojerusan.RSButtonMetro btn_inscriptions;
    private rojerusan.RSButtonMetro btn_licencias;
    private rojerusan.RSButtonMetro btn_matriculas;
    private javax.swing.JButton btn_menu;
    private rojerusan.RSButtonMetro btn_oec;
    private rojerusan.RSButtonMetro btn_peri_aca;
    private rojerusan.RSButtonMetro btn_seminarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JPanel panel_master;
    private javax.swing.JPanel panel_menu;
    private javax.swing.JPanel panel_menu_calificaciones;
    private javax.swing.JScrollPane sc_menu;
    private javax.swing.JScrollPane sc_ventanas;
    // End of variables declaration//GEN-END:variables
}
