/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas_paneles;

import Reportes.Reportes;
import controlador.Main;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import tabla.MyScrollbarUI;

/**
 *
 * @author Danilo
 */
public class Cronogrma_actividades extends javax.swing.JPanel {

    public String fecha_general = "";
    public String hora_general = "";
    public int codigo_general = 0;
    private int estado_busqueda = 0;
 

    /**
     * Creates new form Panel_Home
     */
    public Cronogrma_actividades() {
        initComponents();
        // jLabel6.setBorder(no);

        docente_menu.getVerticalScrollBar().setUI(new MyScrollbarUI());
        docente_menu.getHorizontalScrollBar().setUI(new MyScrollbarUI());

//
//        consutarTabla_Diplomados();
        control_botones();
        nofocus();
        vaciar_cajas();

        // Tabla_actividades.setColumnModel(columnModel);
        // 
        Tabla_actividades.setRowHeight(30);

        // Tabla_actividades.addRowSelectionInterval(0, 3);
        // modelo.addColumn
        
 txt_fecha.setEnabled(false);
 txt_hora.setEnambledButton(false);

    evento_fecha(txt_fecha);
  
                
 //Main.r.tiempo_updateTable=20000;
    }
    
         

    ////conex
    String direccionBD = "jdbc:mysql://localhost:3307/seprytsa";
    String usuarioBD = "root";
    String contraBD = "";
    // Instanciamos la clase conectar 
    modelo.conectar cone1 = new modelo.conectar();
    // realizamos la conexion
    public Connection cn = cone1.conexion(direccionBD, usuarioBD, contraBD);
    // la conexion se hereda en cn
 
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_buscar = new rojerusan.RSButtonMetro();
        cbox_buscar = new rojerusan.RSComboMetro();
        txt_hora = new org.bolivia.time.TimeChooser();
        txt_fecha = new com.toedter.calendar.JDateChooser();
        btn_nuevo = new rojerusan.RSButtonMetro();
        docente_menu = new javax.swing.JScrollPane();
        Tabla_actividades = new rojerusan.RSTableMetro();
        txt_fh = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(21, 96, 136));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_menu/cron_activi_52px_1.png"))); // NOI18N
        jLabel1.setText(" Actividades para el día de hoy");

        btn_buscar.setBackground(new java.awt.Color(21, 96, 136));
        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_menu/buscar_52px.png"))); // NOI18N
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        cbox_buscar.setBackground(new java.awt.Color(21, 96, 136));
        cbox_buscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 96, 136), 3));
        cbox_buscar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Buscar Por..", "Fecha", "Fecha y Hora" }));
        cbox_buscar.setActionCommand("comboBoxChanged\nd\nd\nd\nd\nd");
        cbox_buscar.setColorArrow(new java.awt.Color(21, 96, 136));
        cbox_buscar.setColorBorde(new java.awt.Color(21, 96, 136));
        cbox_buscar.setColorFondo(new java.awt.Color(21, 96, 136));
        cbox_buscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbox_buscar.setName(""); // NOI18N
        cbox_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_buscarActionPerformed(evt);
            }
        });

        txt_hora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 96, 136), 3));
        txt_hora.setToolTipText("asd");
        txt_hora.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_horaCaretUpdate(evt);
            }
        });

        txt_fecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 96, 136), 3));
        txt_fecha.setForeground(new java.awt.Color(21, 96, 136));
        txt_fecha.setDateFormatString("dd-MM-yyyy");
        txt_fecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(cbox_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbox_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_nuevo.setBackground(new java.awt.Color(21, 96, 136));
        btn_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_menu/nuevo_52px.png"))); // NOI18N
        btn_nuevo.setText("Agregar Actividad");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });

        docente_menu.setBackground(new java.awt.Color(21, 96, 136));

        Tabla_actividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        Tabla_actividades.setColorBackgoundHead(new java.awt.Color(21, 96, 136));
        Tabla_actividades.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        Tabla_actividades.setColorBordeHead(new java.awt.Color(21, 96, 136));
        Tabla_actividades.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        Tabla_actividades.setColorFilasForeground1(new java.awt.Color(21, 96, 136));
        Tabla_actividades.setColorFilasForeground2(new java.awt.Color(21, 96, 136));
        Tabla_actividades.setColorSelBackgound(new java.awt.Color(27, 108, 155));
        Tabla_actividades.setFuenteFilas(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Tabla_actividades.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Tabla_actividades.setFuenteHead(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Tabla_actividades.setGridColor(new java.awt.Color(255, 255, 255));
        Tabla_actividades.setSelectionBackground(new java.awt.Color(21, 96, 136));
        Tabla_actividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_actividadesMouseClicked(evt);
            }
        });
        docente_menu.setViewportView(Tabla_actividades);

        txt_fh.setBackground(new java.awt.Color(21, 96, 136));
        txt_fh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_fh.setForeground(new java.awt.Color(21, 96, 136));
        txt_fh.setText("      fecha    hora");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_fh, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(docente_menu)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fh, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(docente_menu, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        // TODO add your handling code here:

        Cronograma_Actividades_SET wa = new Cronograma_Actividades_SET(null, true);

        wa.setVisible(true);

//         nuevo();
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void cbox_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_buscarActionPerformed
        try {
            String strFecha = "2018-03-11";
                    SimpleDateFormat formatoDelTexto = new SimpleDateFormat("yyyy-MM-dd");
                    Date fecha = null;
                    fecha = formatoDelTexto.parse(strFecha);
            // TODO add your handling code here:
            String Campo = cbox_buscar.getSelectedItem().toString();
            switch (Campo) {
                //Buscar Por.., Código, Nombre, Apellido
                case "Buscar Por..":
                    txt_hora.setEnambledButton(false);
                    txt_fecha.setEnabled(false);
                    /// txt_fecha.setBacgroudText(new java.awt.Color(21,96,136));
                    
                    
                    txt_fecha.setDate(fecha);
                    txt_hora.setText("00:00:00");
                    estado_busqueda = 0;
                    
              
                    
                    
                    break;
                    
                case "Fecha":
                    txt_fecha.setDate(fecha);
                    txt_hora.setText("00:00:00");
                    txt_hora.setEnambledButton(false);
                    txt_fecha.setEnabled(true);
                    
                    
                    //txt_fecha.setDate(null);
                    estado_busqueda = 1;
                    
                    
                    break;
                case "Hora":
                    
                    txt_hora.setEnambledButton(true);
                    txt_fecha.setEnabled(false);
                    
                    
                    //txt_fecha.setDate(null);
                    estado_busqueda = 2;
                    
                    break;
                    
                    
                case "Fecha y Hora":
                    txt_fecha.setDate(fecha);
                    txt_hora.setText("00:00:00");
                    txt_fecha.setEnabled(true);
                    txt_hora.setEnambledButton(true);
                    btn_buscar.setEnabled(true);
                    
                    
                    
                    estado_busqueda = 3;
                    
                    break;
                    
            }
        } catch (ParseException ex) {
            Logger.getLogger(Cronogrma_actividades.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_cbox_buscarActionPerformed
    public void atender(int result) {
        if (result == 1) {

            try {

                PreparedStatement pst = cn.prepareStatement("UPDATE `cronograma_actividades` SET `Estado_cac` = ? WHERE `cronograma_actividades`.`cod_cac` = " + codigo_general + "");

                pst.setInt(1, 1);

                pst.executeUpdate();
                //alerta("Notificación", "Datos se actualizaron exitosamente ", "/Img_alertas/satisfactoriamente_100px.png");

            } catch (SQLException e) {
                // JOptionPane.showMessageDialog(null, "ERROR AL GUARDAR LOS DATOS" + e.getMessage());
                alerta("Error", "No se pudo actualizar los datos " + e, "/Img_alertas/Error_100px.png");
            }

            consutarTabla_Salidad_Actividades(fecha_general, hora_general);
            btn_True_false();
            vaciar_cajas();

        }
    }


    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        try {
               
             String formato="yyyy-MM-dd";
                Date date=txt_fecha.getDate();
                SimpleDateFormat sdf=new SimpleDateFormat(formato);
                String fecha= sdf.format(date);
               // JOptionPane.showMessageDialog(null,fecha); 
                String Hora=txt_hora.getText().toString();
;                
                
                String Sql="SELECT cronograma_actividades.cod_cac,cronograma_actividades.Asunto_cac,cronograma_actividades.hora_cac FROM cronograma_actividades WHERE cronograma_actividades.fechacha_cac='"+fecha+"'   AND cronograma_actividades.hora_cac>='"+Hora+"'";
                consutaBD_porfechas(Sql);
            
           
           //  Main.r.tiempo_updateTable=5000000;
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void Tabla_actividadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_actividadesMouseClicked
        try {

            int fila = Tabla_actividades.getSelectedRow();

            if (fila > -1) {
                //  Txt_Codigo.setText(Integer.toString(fila));
                codigo_general = Integer.parseInt(Tabla_actividades.getValueAt(fila, 0).toString());
                //   btn_atender.setEnabled(true);

            
            try {
                Statement estado;
                String asunto = "";
                String Detalle = "";
                estado = cn.createStatement();
                ResultSet resultado = estado.executeQuery("SELECT cronograma_actividades.Asunto_cac,cronograma_actividades.actividad_cac FROM cronograma_actividades WHERE cronograma_actividades.cod_cac=" + codigo_general + "");

                while (resultado.next()) {
                    asunto = resultado.getString(1);
                    Detalle = resultado.getString(2);

                    detalle(asunto, Detalle);
                }
            } catch (Exception e) {
            }
            }
        } catch (Exception ex) {
            // Logger.getLogger(Docentes.class.getName()).log(Level.SEVERE, null, ex);
            alerta("Error", "No a seleccionado la opcion Nuevo" + ex, "/Img_alertas/Error_100px.png");
        }

    }//GEN-LAST:event_Tabla_actividadesMouseClicked

    private void txt_horaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_horaCaretUpdate
//     
// TODO add your handling code here:



if(estado_busqueda ==2 && evt.getMark()==8){
   
           
}else{
   
      
}
        
    }//GEN-LAST:event_txt_horaCaretUpdate

    public void detalle(String asunto, String detalle) {

        Actividades_Detalle dt = new Actividades_Detalle(null, true);
        dt.txt_asunto_general.setText(asunto);
        dt.txt_tarea_general.setText(detalle);

        dt.setVisible(true);
    }

    public void consutarTabla_Salidad_Actividades(String fecha, String hora) {

        String consultaBD = "SELECT cronograma_actividades.cod_cac,cronograma_actividades.Asunto_cac,cronograma_actividades.hora_cac FROM cronograma_actividades \n"
                + " WHERE cronograma_actividades.fechacha_cac=" + fecha + "\n"
                + " AND cronograma_actividades.hora_cac>" + hora + " AND cronograma_actividades.Estado_cac=0";
        //   JOptionPane.showMessageDialog(docente_menu, consultaBD);
        javax.swing.JTable Tabla = this.Tabla_actividades;
        // Enviamos los parametros para la consulta de la tabla
        //  conexion    consulta de la base de datos y el nombre de la tabla
        String cabesera[] = {"Código", "Asunto", "Hora"};
        cone1.GetTabla_Sincabeseras_sql_bd(cn, consultaBD, Tabla, cabesera);

    }

    
 public void consutaBD_porfechas(String txtSQL) {
     try {
         
           Busquedad_Actividades dt = new Busquedad_Actividades(null, true);
     
       String consultaBD =txtSQL;
        javax.swing.JTable Tabla = dt.Tabla_actividades2;
        String cabesera[] = {"Código", "Asunto", "Hora"};
        cone1.GetTabla_Sincabeseras_sql_bd(cn, consultaBD, Tabla, cabesera);  
        
        
         dt.setVisible(true);
     
        
     } catch (Exception e) {
     }
        

    }
    public void consutaBD_sinfiltros(String Campo, String txtSQL) {

        String consultaBD = "SELECT * FROM `diplomados` WHERE " + Campo + "='" + txtSQL + "'";
        // String consultaBD = "SELECT * FROM `docente` WHERE " + Campo + " LIKE '" + txtSQL + "_%'";
        //JOptionPane.showMessageDialog(null, consultaBD);
        javax.swing.JTable Tabla = this.Tabla_actividades;
        // Enviamos los parametros para la consulta de la tabla
        //  conexion    consulta de la base de datos y el nombre de la tabla
        String cabesera[] = {"Código", "Nombre", "Número de Módulos"};
        cone1.GetTabla_Sincabeseras_sql_bd(cn, consultaBD, Tabla, cabesera);

    }

    public void control_botones() {
        try {
            String strFecha = "2018-03-11";
            SimpleDateFormat formatoDelTexto = new SimpleDateFormat("yyyy-MM-dd");
            Date fecha = null;
            fecha = formatoDelTexto.parse(strFecha);
//        btn_guardar.setEnabled(false);
btn_nuevo.setEnabled(true);
// btn_atender.setEnabled(false);

txt_hora.setEnabled(false);
txt_fecha.setEnabled(true);
txt_fecha.setDate(fecha);
txt_hora.setText("00:00:00");
btn_buscar.setEnabled(false);
        } catch (ParseException ex) {
            Logger.getLogger(Cronogrma_actividades.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void alerta(String titulo, String texto, String dir_img) {

        Alertas wa = new Alertas(null, true);
        wa.txt_titu.setText(titulo);
        wa.txt_txt.setText(texto);

        wa.txt_img.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir_img)));

        wa.setVisible(true);
    }

    public int confirmar(String titulo, String texto, String dir_img) {

        int estatus = 9;
        Alertas wa = new Alertas(null, true);
        wa.txt_titu.setText(titulo);
        wa.txt_txt.setText(texto);

        wa.txt_img.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir_img)));

        wa.setVisible(true);

        estatus = wa.respuesta;

        return estatus;
    }

    private void nofocus() {
        btn_nuevo.setFocusPainted(false);
        // btn_atender.setFocusPainted(false);

//        btn_guardar.setFocusPainted(false);
    }

    private void vaciar_cajas() {
//        txt_nombre.setText("");
//       
//        cbox_n_modulos.setSelectedIndex(0);
//         ;
//        txt_codigo.setText("");
//
//        txt_nombre.setEnabled(false);
//        
//        cbox_n_modulos.setEnabled(false);
//        
//        txt_codigo.setEnabled(false);
//        Tabla_actividades.setEnabled(false);
//        txt_buscar.setEnabled(false);

    }

    private void btn_True_false() {
//        btn_guardar.setEnabled(false);
        btn_nuevo.setEnabled(true);
        //btn_atender.setEnabled(false);

        //Tabla_actividades.setEnabled(false);
        
        txt_hora.setText("Hora:");
        txt_hora.setEditable(false);
        
        txt_fecha.setEnabled(false);
    }

    private void nuevo() {
//        btn_guardar.setEnabled(true);
        btn_nuevo.setEnabled(false);
        //  btn_atender.setEnabled(true);

//        txt_nombre.setEnabled(true);
//       
//        cbox_n_modulos.setEnabled(true);
//       
//        txt_codigo.setEnabled(true);
        Tabla_actividades.setEnabled(true);

    }
    
    
    
  private void  evento_fecha(com.toedter.calendar.JDateChooser  componente){
      
      try {
          componente.getDateEditor().addPropertyChangeListener(new PropertyChangeListener(){ 
        public void propertyChange(PropertyChangeEvent e) {
            
            if(estado_busqueda ==1 && e.getPropertyName()=="date"){
   
                String formato="yyyy-MM-dd";
                Date date=txt_fecha.getDate();
                SimpleDateFormat sdf=new SimpleDateFormat(formato);
                String fecha= sdf.format(date);
               // JOptionPane.showMessageDialog(null,fecha); 
                
                
                
                String Sql="SELECT cronograma_actividades.cod_cac,cronograma_actividades.Asunto_cac,cronograma_actividades.hora_cac FROM cronograma_actividades WHERE cronograma_actividades.fechacha_cac='"+fecha+"'";
                consutaBD_porfechas(Sql);
                
                  // Main.r.tiempo_updateTable=5000000;
  
}
    
        }
});
      } catch (Exception e) {
      }
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSTableMetro Tabla_actividades;
    private rojerusan.RSButtonMetro btn_buscar;
    private rojerusan.RSButtonMetro btn_nuevo;
    public rojerusan.RSComboMetro cbox_buscar;
    private javax.swing.JScrollPane docente_menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser txt_fecha;
    public javax.swing.JLabel txt_fh;
    private org.bolivia.time.TimeChooser txt_hora;
    // End of variables declaration//GEN-END:variables
}

