/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas_paneles;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tabla.MyScrollbarUI;

/**
 *
 * @author Danilo
 */
public class Matriculas extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Home
     */
    public Matriculas() {
        initComponents();
        // jLabel6.setBorder(no);

        docente_menu.getVerticalScrollBar().setUI(new MyScrollbarUI());
        docente_menu.getHorizontalScrollBar().setUI(new MyScrollbarUI());

        consutarTabla_Matriculas();
        control_botones();
        nofocus();
        vaciar_cajas();

    }

    ////conex
    String direccionBD = "jdbc:mysql://localhost:3307/seprytsa";
    String usuarioBD = "root";
    String contraBD = "";
    // Instanciamos la clase conectar 
    modelo.conectar cone1 = new modelo.conectar();
    // realizamos la conexion
    public Connection cn = cone1.conexion(direccionBD, usuarioBD, contraBD);
    // la conexion se hereda en cn

    int caja1 = 0;
    int caja2 = 0;
    int caja3 = 0;
    int caja4 = 0;
    int caja5 = 0;
    int caja6 = 0;
    int caja7 = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        docente_menu = new javax.swing.JScrollPane();
        Tabla_Matriculas = new rojerusan.RSTableMetro();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_buscar = new rojerusan.RSButtonMetro();
        cbox_buscar = new rojerusan.RSComboMetro();
        txt_buscar = new rojerusan.RSMetroTextPlaceHolder();
        btn_nuevo = new rojerusan.RSButtonMetro();
        txt_cod_estudiante = new rojerusan.RSMetroTextPlaceHolder();
        txt_codigo = new rojerusan.RSMetroTextPlaceHolder();
        txt_cod_p_academico = new rojerusan.RSMetroTextPlaceHolder();
        txt_cod_horario = new rojerusan.RSMetroTextPlaceHolder();
        txt_cod_diplomado = new rojerusan.RSMetroTextPlaceHolder();
        btn_actualizar = new rojerusan.RSButtonMetro();
        btn_eliminar = new rojerusan.RSButtonMetro();
        btn_refrescar = new rojerusan.RSButtonMetro();
        btn_reportes = new rojerusan.RSButtonMetro();
        btn_guardar = new rojerusan.RSButtonMetro();
        btn_cod_est = new rojerusan.RSButtonMetro();
        btn_cod_p_academico = new rojerusan.RSButtonMetro();
        btn_cod_horario = new rojerusan.RSButtonMetro();
        btn_cod_diplomado = new rojerusan.RSButtonMetro();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        docente_menu.setBackground(new java.awt.Color(21, 96, 136));

        Tabla_Matriculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla_Matriculas.setColorBackgoundHead(new java.awt.Color(21, 96, 136));
        Tabla_Matriculas.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        Tabla_Matriculas.setColorBordeHead(new java.awt.Color(21, 96, 136));
        Tabla_Matriculas.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        Tabla_Matriculas.setColorFilasForeground1(new java.awt.Color(21, 96, 136));
        Tabla_Matriculas.setColorFilasForeground2(new java.awt.Color(21, 96, 136));
        Tabla_Matriculas.setColorSelBackgound(new java.awt.Color(27, 108, 155));
        Tabla_Matriculas.setGridColor(new java.awt.Color(255, 255, 255));
        Tabla_Matriculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_MatriculasMouseClicked(evt);
            }
        });
        docente_menu.setViewportView(Tabla_Matriculas);

        jPanel1.setBackground(new java.awt.Color(21, 96, 136));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_menu/matriculas_52px.png"))); // NOI18N
        jLabel1.setText("       Matrículas");

        btn_buscar.setBackground(new java.awt.Color(21, 96, 136));
        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_menu/buscar_52px.png"))); // NOI18N
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        cbox_buscar.setBackground(new java.awt.Color(21, 96, 136));
        cbox_buscar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Buscar Por..", "Código", "Código del estudiante", "Código del periodo académico" }));
        cbox_buscar.setActionCommand("comboBoxChanged\nd\nd\nd\nd\nd");
        cbox_buscar.setColorArrow(new java.awt.Color(21, 96, 136));
        cbox_buscar.setColorBorde(new java.awt.Color(21, 96, 136));
        cbox_buscar.setColorFondo(new java.awt.Color(21, 96, 136));
        cbox_buscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbox_buscar.setName(""); // NOI18N
        cbox_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_buscarActionPerformed(evt);
            }
        });

        txt_buscar.setForeground(new java.awt.Color(27, 108, 155));
        txt_buscar.setBorderColor(new java.awt.Color(21, 96, 136));
        txt_buscar.setBotonColor(new java.awt.Color(21, 96, 136));
        txt_buscar.setCaretColor(new java.awt.Color(21, 96, 136));
        txt_buscar.setDisabledTextColor(new java.awt.Color(102, 102, 255));
        txt_buscar.setPhColor(new java.awt.Color(27, 108, 155));
        txt_buscar.setPlaceholder("Buscar:");
        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbox_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbox_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17))))
        );

        btn_nuevo.setBackground(new java.awt.Color(21, 96, 136));
        btn_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_menu/nuevo_52px.png"))); // NOI18N
        btn_nuevo.setText("Nuevo");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });

        txt_cod_estudiante.setForeground(new java.awt.Color(27, 108, 155));
        txt_cod_estudiante.setBorderColor(new java.awt.Color(21, 96, 136));
        txt_cod_estudiante.setBotonColor(new java.awt.Color(21, 96, 136));
        txt_cod_estudiante.setCaretColor(new java.awt.Color(21, 96, 136));
        txt_cod_estudiante.setDisabledTextColor(new java.awt.Color(27, 108, 155));
        txt_cod_estudiante.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_cod_estudiante.setPhColor(new java.awt.Color(27, 108, 155));
        txt_cod_estudiante.setPlaceholder("Código del Estudiante:");
        txt_cod_estudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cod_estudianteActionPerformed(evt);
            }
        });
        txt_cod_estudiante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cod_estudianteKeyTyped(evt);
            }
        });

        txt_codigo.setForeground(new java.awt.Color(27, 108, 155));
        txt_codigo.setBorderColor(new java.awt.Color(21, 96, 136));
        txt_codigo.setBotonColor(new java.awt.Color(21, 96, 136));
        txt_codigo.setCaretColor(new java.awt.Color(21, 96, 136));
        txt_codigo.setDisabledTextColor(new java.awt.Color(102, 102, 255));
        txt_codigo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_codigo.setPhColor(new java.awt.Color(27, 108, 155));
        txt_codigo.setPlaceholder("Código de la Matrícula:");

        txt_cod_p_academico.setForeground(new java.awt.Color(27, 108, 155));
        txt_cod_p_academico.setBorderColor(new java.awt.Color(21, 96, 136));
        txt_cod_p_academico.setBotonColor(new java.awt.Color(21, 96, 136));
        txt_cod_p_academico.setCaretColor(new java.awt.Color(21, 96, 136));
        txt_cod_p_academico.setDisabledTextColor(new java.awt.Color(27, 108, 155));
        txt_cod_p_academico.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_cod_p_academico.setPhColor(new java.awt.Color(27, 108, 155));
        txt_cod_p_academico.setPlaceholder("Códi d. peri. Académico");
        txt_cod_p_academico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cod_p_academicoActionPerformed(evt);
            }
        });
        txt_cod_p_academico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cod_p_academicoKeyTyped(evt);
            }
        });

        txt_cod_horario.setForeground(new java.awt.Color(27, 108, 155));
        txt_cod_horario.setBorderColor(new java.awt.Color(21, 96, 136));
        txt_cod_horario.setBotonColor(new java.awt.Color(21, 96, 136));
        txt_cod_horario.setCaretColor(new java.awt.Color(21, 96, 136));
        txt_cod_horario.setDisabledTextColor(new java.awt.Color(27, 108, 155));
        txt_cod_horario.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_cod_horario.setPhColor(new java.awt.Color(27, 108, 155));
        txt_cod_horario.setPlaceholder("Código del Horario");
        txt_cod_horario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cod_horarioActionPerformed(evt);
            }
        });
        txt_cod_horario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cod_horarioKeyTyped(evt);
            }
        });

        txt_cod_diplomado.setForeground(new java.awt.Color(27, 108, 155));
        txt_cod_diplomado.setBorderColor(new java.awt.Color(21, 96, 136));
        txt_cod_diplomado.setBotonColor(new java.awt.Color(21, 96, 136));
        txt_cod_diplomado.setCaretColor(new java.awt.Color(21, 96, 136));
        txt_cod_diplomado.setDisabledTextColor(new java.awt.Color(27, 108, 155));
        txt_cod_diplomado.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_cod_diplomado.setPhColor(new java.awt.Color(27, 108, 155));
        txt_cod_diplomado.setPlaceholder("Código del  Diplomado");
        txt_cod_diplomado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cod_diplomadoActionPerformed(evt);
            }
        });

        btn_actualizar.setBackground(new java.awt.Color(21, 96, 136));
        btn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_menu/actualizar_52px.png"))); // NOI18N
        btn_actualizar.setText("Actualizar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        btn_eliminar.setBackground(new java.awt.Color(21, 96, 136));
        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_menu/eliminar_52px.png"))); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_refrescar.setBackground(new java.awt.Color(21, 96, 136));
        btn_refrescar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_menu/refrescar52px.png"))); // NOI18N
        btn_refrescar.setText("Refrescar");
        btn_refrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refrescarActionPerformed(evt);
            }
        });

        btn_reportes.setBackground(new java.awt.Color(21, 96, 136));
        btn_reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_menu/reportes52px.png"))); // NOI18N
        btn_reportes.setText("Reportes");
        btn_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportesActionPerformed(evt);
            }
        });

        btn_guardar.setBackground(new java.awt.Color(21, 96, 136));
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_menu/guardar_52px.png"))); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_cod_est.setBackground(new java.awt.Color(21, 96, 136));
        btn_cod_est.setText("Seleccionar:");
        btn_cod_est.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cod_estActionPerformed(evt);
            }
        });

        btn_cod_p_academico.setBackground(new java.awt.Color(21, 96, 136));
        btn_cod_p_academico.setText("Seleccionar:");
        btn_cod_p_academico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cod_p_academicoActionPerformed(evt);
            }
        });

        btn_cod_horario.setBackground(new java.awt.Color(21, 96, 136));
        btn_cod_horario.setText("Seleccionar:");
        btn_cod_horario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cod_horarioActionPerformed(evt);
            }
        });

        btn_cod_diplomado.setBackground(new java.awt.Color(21, 96, 136));
        btn_cod_diplomado.setText("Seleccionar:");
        btn_cod_diplomado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cod_diplomadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_cod_diplomado, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(txt_cod_estudiante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txt_cod_p_academico, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txt_cod_horario, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_cod_p_academico, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cod_horario, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cod_diplomado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cod_est, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txt_codigo, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn_reportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn_refrescar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(docente_menu)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_refrescar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(docente_menu, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_cod_est, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cod_estudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_cod_p_academico, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cod_p_academico, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_cod_horario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cod_horario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_cod_diplomado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cod_diplomado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
         try {

            String codigo = txt_codigo.getText().toString();
            String cod_estudiante=txt_cod_estudiante.getText().toString();
            String cod_p_aca=txt_cod_p_academico.getText().toString();
            int cod_horario = Integer.parseInt(txt_cod_horario.getText().toString());
            String cod_diplomados = txt_cod_diplomado.getText().toString();
           int status=2;


            try {
                PreparedStatement pst;
                pst = cn.prepareStatement("INSERT INTO `matricula`(`cod_mat`, `cod_est`, `cod_pa`, `cod_hor`, `cod_dip`) VALUES (?,?,?,?,?)");

                pst.setString(1, codigo);
                pst.setString(2, cod_estudiante);
                pst.setString(3, cod_p_aca);
                pst.setInt(4,cod_horario);
                pst.setString(5, cod_diplomados);
                pst.executeUpdate();
               
                
                
                try {
                   PreparedStatement ps;
                ps = cn.prepareStatement("INSERT INTO `calificacion_1`( `cod_mat`, `valor_cal`, `faltas`) VALUES (?,?,?)");
                
                ps.setString(1, codigo);
                ps.setFloat(2, 0);
                ps.setInt(3, 0);
                  ps.executeUpdate();
               
                
                
                } catch (SQLException ex) {
                    alerta("Error", "No se Pudo insertar los datos" + ex, "/Img_alertas/Error_100px.png");
                }
                
                try {
                   PreparedStatement pss;
                pss = cn.prepareStatement("INSERT INTO `calificacion_2`( `cod_mat`, `valor_cal`, `faltas`) VALUES (?,?,?)");
                
                pss.setString(1, codigo);
                pss.setFloat(2, 0);
                pss.setInt(3, 0);
                pss.executeUpdate();
               
                
                
                } catch (SQLException ex) {
                    alerta("Error", "No se Pudo insertar los datos" + ex, "/Img_alertas/Error_100px.png");
                }
                
                try {
                   PreparedStatement psss;
                psss = cn.prepareStatement("INSERT INTO `calificacion_3`( `cod_mat`, `valor_cal`, `faltas`) VALUES (?,?,?)");
                
                psss.setString(1, codigo);
                psss.setFloat(2, 0);
                psss.setInt(3, 0);
                psss.executeUpdate();
               
                
                
                } catch (SQLException ex) {
                    alerta("Error", "No se Pudo insertar los datos" + ex, "/Img_alertas/Error_100px.png");
                }
                
                 try {
                   PreparedStatement pssss;
                pssss = cn.prepareStatement("INSERT INTO `calificacion_4`( `cod_mat`, `valor_cal`, `faltas`) VALUES (?,?,?)");
                
                pssss.setString(1, codigo);
                pssss.setFloat(2, 0);
                pssss.setInt(3, 0);
                pssss.executeUpdate();
               
                
                
                } catch (SQLException ex) {
                    alerta("Error", "No se Pudo insertar los datos" + ex, "/Img_alertas/Error_100px.png");
                }
                
                
                
                
                
                
                
                
                alerta("Notificación", "Datos Guardados exitosamente", "/Img_alertas/satisfactoriamente_100px.png");
                
                //           JOptionPane.showMessageDialog(null, "se guardo el datos " + Tabla_dis.getValueAt(i, 0).toString() + " y " + Tabla_dis.getValueAt(i, 1).toString());
            } catch (SQLException ex) {

                alerta("Error", "No se pudo guardar " + ex, "/Img_alertas/Error_100px.png");

                Logger.getLogger(Docentes.class.getName()).log(Level.SEVERE, null, ex);
            }

            consutarTabla_Matriculas();
            btn_True_false();
            vaciar_cajas();

        } catch (Exception ex) {

            alerta("Error", "Faltan Campos de LLenar " + ex, "/Img_alertas/Error_100px.png");

            txt_codigo.requestFocus();

        }

        
    }//GEN-LAST:event_btn_guardarActionPerformed

    
    
    
    private void btn_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_reportesActionPerformed

    private void btn_refrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refrescarActionPerformed
        // TODO add your handling code here:
        consutarTabla_Matriculas();
        control_botones();
        txt_buscar.setText("");
        cbox_buscar. setSelectedIndex(0);
    }//GEN-LAST:event_btn_refrescarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        try {

          
            int res = confirmar("Error", "Seguro que desea eliminar este campo ", "/Img_alertas/Error_100px.png");

            if (res == 1) {

                // TODO add your handling code here:
                String codigo = txt_codigo.getText().toString();
                PreparedStatement pst;
                pst = cn.prepareStatement("DELETE FROM `matricula` WHERE matricula.cod_mat=?");
                pst.setString(1, codigo);
                pst.executeUpdate();
                alerta("Notificación", "Datos eliminados exitosamente", "/Img_alertas/satisfactoriamente_100px.png");
            } else {
                alerta("Notificación", "Se cancelo la operación", "/Img_alertas/satisfactoriamente_100px.png");
            }

        } catch (SQLException ex) {
            alerta("Error", "No se elimino los datos " + ex, "/Img_alertas/Error_100px.png");
        }
        consutarTabla_Matriculas();
        btn_True_false();
        vaciar_cajas();

    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed

        // TODO add your handling code here:
        int res = confirmar("Error", "Seguro que desea actualizar este campo ", "/Img_alertas/Error_100px.png");

        if (res == 1) {

             String codigo = txt_codigo.getText().toString();
            String cod_estudiante=txt_cod_estudiante.getText().toString();
            String cod_p_aca=txt_cod_p_academico.getText().toString();
            int cod_horario = Integer.parseInt(txt_cod_horario.getText().toString());
            String cod_diplomados = txt_cod_diplomado.getText().toString();
           
            //alerta("Notificacion", "Datos Guardados exitosamente" , "/Img_alertas/satisfactoriamente_.png");
            try {

                PreparedStatement pst = cn.prepareStatement("UPDATE `matricula` SET `cod_est`=?,`cod_pa`=?,`cod_hor`=?,`cod_dip`=? WHERE matricula.cod_mat='" + codigo + "'");

                pst.setString(1, cod_estudiante);
                pst.setString(2, cod_p_aca);
                pst.setInt(3,cod_horario);
                pst.setString(4, cod_diplomados);
                

                pst.executeUpdate();
                alerta("Notificación", "Datos se actualizaron exitosamente ", "/Img_alertas/satisfactoriamente_100px.png");

            } catch (SQLException e) {
                // JOptionPane.showMessageDialog(null, "ERROR AL GUARDAR LOS DATOS" + e.getMessage());
                alerta("Error", "No se pudo actualizar los datos " + e, "/Img_alertas/Error_100px.png");
            }

            consutarTabla_Matriculas();
            btn_True_false();
            vaciar_cajas();

        }
        else{
            alerta("Notificación", "Se cancelo la operación", "/Img_alertas/satisfactoriamente_100px.png");
        }
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void txt_cod_diplomadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cod_diplomadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cod_diplomadoActionPerformed

    private void txt_cod_horarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cod_horarioKeyTyped
        // TODO add your handling code here:

        char digito=evt.getKeyChar();

        if(!Character.isDigit(digito)){// si no es un numero
            evt.consume();
        }

    }//GEN-LAST:event_txt_cod_horarioKeyTyped

    private void txt_cod_horarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cod_horarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cod_horarioActionPerformed

    private void txt_cod_p_academicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cod_p_academicoKeyTyped
        // TODO add your handling code here:
        char letra=evt.getKeyChar();
        if(!Character.isLetter(letra) && !Character.isSpaceChar(letra)){// si no es letra
            evt.consume();// cancelo ingreso de la letra
        }
    }//GEN-LAST:event_txt_cod_p_academicoKeyTyped

    private void txt_cod_p_academicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cod_p_academicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cod_p_academicoActionPerformed

    private void txt_cod_estudianteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cod_estudianteKeyTyped
        // TODO add your handling code here:
        char letra=evt.getKeyChar();
        if(!Character.isLetter(letra) && !Character.isSpaceChar(letra)){// si no es letra
            evt.consume();// cancelo ingreso de la letra
        }
    }//GEN-LAST:event_txt_cod_estudianteKeyTyped

    private void txt_cod_estudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cod_estudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cod_estudianteActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        // TODO add your handling code here:

        nuevo();
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void txt_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyReleased
        // TODO add your handling code here:
        //Buscar Por..

        
        
        
        String Campo = cbox_buscar.getSelectedItem().toString();
        String txtSql = txt_buscar.getText().toString();

        String  Campo2= null;
        switch (Campo) {
            //Buscar Por.., Código, Nombre, Apellido
            case "Buscar Por..":

            break;
            case "Código":

            Campo2="cod_mat";
            consutaBD( Campo2,txtSql);

            break;
            case "Código del estudiante":

            Campo2="cod_est";
            consutaBD( Campo2,txtSql);

            break;
            case "Código del periodo académico":

            Campo2="cod_pa";
            consutaBD( Campo2,txtSql);
            break;
        }

    }//GEN-LAST:event_txt_buscarKeyReleased

    private void cbox_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_buscarActionPerformed
        // TODO add your handling code here:
        String Campo=cbox_buscar.getSelectedItem().toString();
        switch (Campo) {
            //Buscar Por.., Código, Nombre, Apellido
            case "Buscar Por..":

            txt_buscar.setEnabled(false);
            consutarTabla_Matriculas();
            btn_True_false();
            vaciar_cajas();
            break;
            case "Código":
            txt_buscar.setEnabled(true);

            nuevo();

            break;
            case "Código del periodo académico":
            txt_buscar.setEnabled(true);
            nuevo();

            break;
            case "Apellido":
            txt_buscar.setEnabled(true);
            nuevo();
            break;
        }

    }//GEN-LAST:event_cbox_buscarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        String Campo=cbox_buscar.getSelectedItem().toString();
        String  Campo2= null;
        String txtSql = txt_buscar.getText().toString();
        switch (Campo) {
            //Buscar Por.., Código, Nombre, Apellido
            case "Buscar Por..":
//Código
//Código del estudiante
//Código del periodo académico
            txt_buscar.setEnabled(false);
            consutarTabla_Matriculas();
            btn_True_false();
            vaciar_cajas();
            nuevo();
            break;
            case "Código":
            Campo2="cod_mat";
            consutaBD_sinfiltros( Campo2,txtSql);

            txt_buscar.setEnabled(true);

            break;
            case "Código del estudiante":

            Campo2="cod_est";
            consutaBD_sinfiltros( Campo2,txtSql);

            txt_buscar.setEnabled(true);

            break;
            case "Código del periodo académico":

            Campo2="cod_pa";
            consutaBD_sinfiltros( Campo2,txtSql);

            txt_buscar.setEnabled(true);

            break;
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void Tabla_MatriculasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_MatriculasMouseClicked
        try {
            // TODO add your handling code here:

            int fila = Tabla_Matriculas.getSelectedRow();

            if (fila > -1) {
                //  Txt_Codigo.setText(Integer.toString(fila));
                txt_codigo.setText(Tabla_Matriculas.getValueAt(fila, 0).toString());
                txt_cod_estudiante.setText(Tabla_Matriculas.getValueAt(fila, 1).toString());
                txt_cod_p_academico.setText(Tabla_Matriculas.getValueAt(fila, 2).toString());
                txt_cod_diplomado.setText(Tabla_Matriculas.getValueAt(fila, 3).toString());
                txt_cod_horario.setText(Tabla_Matriculas.getValueAt(fila, 4).toString());
               
            }
            

        } catch (Exception ex) {
            // Logger.getLogger(Docentes.class.getName()).log(Level.SEVERE, null, ex);
            alerta("Error", "No a seleccionado la opcion Nuevo" + ex, "/Img_alertas/Error_100px.png");
        }

    }//GEN-LAST:event_Tabla_MatriculasMouseClicked

    private void btn_cod_estActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cod_estActionPerformed
        // TODO add your handling code here:
        Busqueda bs=new Busqueda();
        
       bs.setVisible(true);
       bs.Entidad="estudiante";
    }//GEN-LAST:event_btn_cod_estActionPerformed

    private void btn_cod_p_academicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cod_p_academicoActionPerformed
        // TODO add your handling code here:
         Busqueda bs=new Busqueda();
        
       bs.setVisible(true);
       bs.Entidad="periodo_academico";
    }//GEN-LAST:event_btn_cod_p_academicoActionPerformed

    private void btn_cod_horarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cod_horarioActionPerformed
        // TODO add your handling code here:
         Busqueda bs=new Busqueda();
        
       bs.setVisible(true);
       bs.Entidad="horarios";
    }//GEN-LAST:event_btn_cod_horarioActionPerformed

    private void btn_cod_diplomadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cod_diplomadoActionPerformed
        // TODO add your handling code here:
        Busqueda bs=new Busqueda();
        
       bs.setVisible(true);
       bs.Entidad="diplomados";
    }//GEN-LAST:event_btn_cod_diplomadoActionPerformed

    public void consutarTabla_Matriculas() {

        String consultaBD = "SELECT * FROM `matricula`";
        javax.swing.JTable Tabla = this.Tabla_Matriculas;
        // Enviamos los parametros para la consulta de la tabla
        //  conexion    consulta de la base de datos y el nombre de la tabla
        String cabesera[] = {"Código de la Matrícula", "Código del estudiante", "Código del periodo académico", "Código del horario", "Código del diplomado" };
        cone1.GetTabla_Sincabeseras_sql_bd(cn, consultaBD, Tabla, cabesera);

    }

    public void consutaBD(String Campo, String txtSQL) {

        //String consultaBD = "SELECT * FROM `docente` WHERE " + Campo + "='" + txtSQL + "'";
          String consultaBD = "SELECT * FROM `matricula` WHERE " + Campo + " LIKE '" + txtSQL + "_%'";
          //JOptionPane.showMessageDialog(null, consultaBD);
        javax.swing.JTable Tabla = this.Tabla_Matriculas;
        // Enviamos los parametros para la consulta de la tabla
        //  conexion    consulta de la base de datos y el nombre de la tabla
        String cabesera[] = {"Código de la Matrícula", "Código del estudiante", "Código del periodo académico", "Código del horario", "Código del diplomado" };
        cone1.GetTabla_Sincabeseras_sql_bd(cn, consultaBD, Tabla, cabesera);

    }
     public void consutaBD_sinfiltros(String Campo, String txtSQL) {

        String consultaBD = "SELECT * FROM `matricula` WHERE " + Campo + "='" + txtSQL + "'";
         // String consultaBD = "SELECT * FROM `docente` WHERE " + Campo + " LIKE '" + txtSQL + "_%'";
          //JOptionPane.showMessageDialog(null, consultaBD);
        javax.swing.JTable Tabla = this.Tabla_Matriculas;
        // Enviamos los parametros para la consulta de la tabla
        //  conexion    consulta de la base de datos y el nombre de la tabla
        String cabesera[] = {"Código de la Matrícula", "Código del estudiante", "Código del periodo académico", "Código del horario", "Código del diplomado" };
        cone1.GetTabla_Sincabeseras_sql_bd(cn, consultaBD, Tabla, cabesera);

    }

    public void control_botones() {
        btn_guardar.setEnabled(false);
        btn_nuevo.setEnabled(true);
        btn_actualizar.setEnabled(false);
        btn_eliminar.setEnabled(false);
        btn_reportes.setEnabled(true);
        btn_refrescar.setEnabled(true);
    }

    public void alerta(String titulo, String texto, String dir_img) {

        Alertas wa = new Alertas(null, true);
        wa.txt_titu.setText(titulo);
        wa.txt_txt.setText(texto);

        wa.txt_img.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir_img)));

        wa.setVisible(true);
    }

    public int confirmar(String titulo, String texto, String dir_img) {

        int estatus = 9;
        Alertas wa = new Alertas(null, true);
        wa.txt_titu.setText(titulo);
        wa.txt_txt.setText(texto);

        wa.txt_img.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir_img)));

        wa.setVisible(true);

        estatus = wa.respuesta;

        return estatus;
    }

    private void nofocus() {
        btn_nuevo.setFocusPainted(false);
        btn_actualizar.setFocusPainted(false);
        btn_eliminar.setFocusPainted(false);
        btn_reportes.setFocusPainted(false);
        btn_refrescar.setFocusPainted(false);
        btn_guardar.setFocusPainted(false);

    }

    private void vaciar_cajas() {
        txt_cod_estudiante.setText("");
        txt_cod_p_academico.setText("");
        txt_cod_horario.setText("");
        txt_cod_diplomado.setText("");
        
        txt_codigo.setText("");

        txt_cod_estudiante.setEnabled(false);
        txt_cod_p_academico.setEnabled(false);
        txt_cod_horario.setEnabled(false);
        txt_cod_diplomado.setEnabled(false);
        
        txt_codigo.setEnabled(false);
        Tabla_Matriculas.setEnabled(false);
        txt_buscar.setEnabled(false);
        
        btn_cod_est.setEnabled(false);
        btn_cod_p_academico.setEnabled(false);
        btn_cod_horario.setEnabled(false);
        btn_cod_diplomado.setEnabled(false);
         
    }

    private void btn_True_false() {
        btn_guardar.setEnabled(false);
        btn_nuevo.setEnabled(true);
        btn_actualizar.setEnabled(false);
        btn_eliminar.setEnabled(false);
        btn_reportes.setEnabled(true);
        btn_refrescar.setEnabled(true);
        Tabla_Matriculas.setEnabled(false);
      
    }
    private void nuevo(){
        btn_guardar.setEnabled(true);
        btn_nuevo.setEnabled(false);
        btn_actualizar.setEnabled(true);
        btn_eliminar.setEnabled(true);
        btn_reportes.setEnabled(true);
        btn_refrescar.setEnabled(true);

        txt_cod_estudiante.setEnabled(true);
        txt_cod_p_academico.setEnabled(true);
        txt_cod_horario.setEnabled(true);
        txt_cod_diplomado.setEnabled(true);
      
        txt_codigo.setEnabled(true);
        Tabla_Matriculas.setEnabled(true);
        
        btn_cod_est.setEnabled(true);
        btn_cod_p_academico.setEnabled(true);
        btn_cod_horario.setEnabled(true);
        btn_cod_diplomado.setEnabled(true);

        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSTableMetro Tabla_Matriculas;
    private rojerusan.RSButtonMetro btn_actualizar;
    private rojerusan.RSButtonMetro btn_buscar;
    private rojerusan.RSButtonMetro btn_cod_diplomado;
    private rojerusan.RSButtonMetro btn_cod_est;
    private rojerusan.RSButtonMetro btn_cod_horario;
    private rojerusan.RSButtonMetro btn_cod_p_academico;
    private rojerusan.RSButtonMetro btn_eliminar;
    private rojerusan.RSButtonMetro btn_guardar;
    private rojerusan.RSButtonMetro btn_nuevo;
    private rojerusan.RSButtonMetro btn_refrescar;
    private rojerusan.RSButtonMetro btn_reportes;
    private rojerusan.RSComboMetro cbox_buscar;
    private javax.swing.JScrollPane docente_menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private rojerusan.RSMetroTextPlaceHolder txt_buscar;
    public rojerusan.RSMetroTextPlaceHolder txt_cod_diplomado;
    public rojerusan.RSMetroTextPlaceHolder txt_cod_estudiante;
    public rojerusan.RSMetroTextPlaceHolder txt_cod_horario;
    public rojerusan.RSMetroTextPlaceHolder txt_cod_p_academico;
    private rojerusan.RSMetroTextPlaceHolder txt_codigo;
    // End of variables declaration//GEN-END:variables
}
